# Generated by Django 5.0.1 on 2024-02-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('remaining_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(max_length=256)),
                ('Number_of_Items', models.IntegerField(blank=True, null=True)),
                ('Date_of_Transaction', models.DateField(auto_now_add=True)),
                ('Item_Retrieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.item')),
            ],
        ),
    ]
