# Generated by Django 5.0.1 on 2024-02-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(max_length=256)),
                ('Item_Retrieved', models.CharField(max_length=256)),
                ('Number_of_Items', models.IntegerField()),
                ('Date_of_Transaction', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
