# Generated by Django 4.2.7 on 2024-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Item_Retrieved',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Number_of_Items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
