# Generated by Django 5.0.2 on 2024-02-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_transaction_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='card',
            new_name='card_Number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Number_of_Items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
